### ISSUE TITLE
Save Story information lifted from onboarding

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#11]
Bear in mind, this data model is tentative! If you think something could be improved, do share any ideas.
- [ ] Add new Story model, linked 1-to-1 to Users (optional FK):
    * `age`: integer
    * `sex`: `"male"` | `"female"` | `"other"`
    * `ethnicity`: string
    * `countryOfOrigin`: string
    * `profession`: string
    * `medicalProblems`: format tbd, it's a short list of texts - possibly an auxiliary table?
    * `isSick`: `"not_sick"` | `"sick"` | `"recovered"`
    * `isTested`: `"positive"` | `"negative"` | `"not_tested"`
- [ ] Hook frontend so that all this information (collected during user onboarding) is stored in the backend with the POST endpoint

**Comment by nditada** [comment]
Having a 1-1 between user table and "story" would make it easier to later increase protection and privacy on data, so 👍 for that.

**Comment by anaPerezGhiglia** [comment]
@pyritewolf "Close contacts" and "Recent travels" should be part of the **Story** model right?

**Comment by pyritewolf** [comment]
@anaPerezGhiglia Whelp, i haven't modeled those! I thought of modeling them as external tables in sepparate issues, to avoid buffing up this one, but yes!

Wanna do it here or in a sepparate issue?

**Comment by anaPerezGhiglia** [comment]
We could separate it in a different issue, and add it to the Story model after (thats why we have migrations, right? 😛). I believe that better have the core fields of the Story working first

I agree with modeling them as external tables 👍
