### ISSUE TITLE
Verify browser compatibility

### ISSUE THREAD

**Issue by nditada** [instedd/oasis#117]
From the consulate:
> When we try to enter the OASIS page on several browsers (Chrome and Explorer), we only get a big black screen.  The page only works with Microsoft Edge, which is not a browser that most of our consular officers have access to from home. 

Let's check which versions of Chrome and IE are working fine.

**Comment by mmuller** [comment]
Currently I am using the following browser versions:
**On macOS:**
Google Chrome 83.0
Firefox 77
Safari 12.1
Opera 68

**On Windows:**
Edge 18

**Comment by mmuller** [comment]
I can get the black screen using IE

**Comment by anaPerezGhiglia** [comment]
@nditada what should we do with this issue? Finally what site are they accessing?
@mmuller the validations you did was accessing https://oasis-stg.instedd.org/ right?
