### ISSUE TITLE
Auto-fill "Country" and "Postal code"

### ISSUE THREAD

**Issue by ste519** [instedd/oasis#132]
When the user input city, the app auto-fill the state and country for them.

**Comment by yus252** [comment]
Loading Issue:

> TypeError: Cannot read property 'map' of undefined
> CriticalQuestions
> src/routes/CriticalQuestions/index.js:389 
>    386 |   <AddIcon />
>    387 | </Fab>
>    388 | <p>Recent Travels</p>
> > 389 | <Pop
>    390 |   ^  label={<ErrorOutlineIcon />}
>    391 |       title={<span></span>}
>    392 |      texts={travelText}

**Comment by yus252** [comment]
> When the user input city, the app auto-fill the state and country for them.
> 
> * [ ]  Change frontend logic
> * [ ]  Change backend
> * [ ]  Change database

**Comment by yus252** [comment]
Please push your code to github. We need this for OASIS 1.0.
