### ISSUE TITLE
Change LocalStorage strategy

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#14]
Currently, we're storing all app information on `localStorage`. This means that if you visit the page, interact, close the tab and return later in the day from the same device & browser your information has been stored.

However, we should rely on the API for storing most information, unless you haven't logged in. On top of that, keeping data both in `localStorage` & the DB means that we need to handle syncing and it can get quite headache-y rather fast.

With that in mind, we need to limit what we're storing in `localStorage`:
- [x] If you're not logged in, we'll submit your `Story` (health information + sympthoms) to the backend, and save in `localStorage` a JWT token that identifies your story.
- [x] _When_ you log in, if there was a  token in your `localStorage` we'll link your `Story` to your brand new `User` and clear the token afterwards
- [x] Once you're logged in, the only information stored in `localStorage` is your user info + auth token in order to persist your session over time. All other information is merely submitted to the backend and store in the Redux store during your navigation session.

**Comment by pyritewolf** [comment]
Hey @ste519 ! I was just about to start laying some groundworks for this one but found it unassigned & in progress 😅 

From the issue history I see you've been interacting with it, let me know if you've made any progress in a branch so I can hop in and add to that!

**Comment by ste519** [comment]
Hi! Previously I used localStorage to persist the redux states, and now I used redux-persist instead, and I have already pushed this change to master in my last pull request.
