### ISSUE TITLE
Unable to fetch symptoms

### ISSUE THREAD

**Issue by yxlin118** [instedd/oasis#143]
On symptoms page, can only see "other symptoms" and not the list of symptoms to select from.

**Comment by pyritewolf** [comment]
Hello @yxlin118 ! A quick check - have you ran the third step in the [setup instructions](https://github.com/instedd/oasis#local-project-setup)? You can also try manually running the [seed data](https://github.com/instedd/oasis#seeding-data).

**Comment by yxlin118** [comment]
@pyritewolf  seeding the data works now. Thanks!
