### ISSUE TITLE
How are you feeling today?

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#20]
After you've finished onboarding, as part of your bottom FAB actions:
- [ ] Add a `DailyCheck` model to the database, associated to the `Story` model (a story may have many daily checks)
- [ ] Add a safe endpoint (same safety degree as Story endpoints)  that allows people to create a new Check
- [x] Add a slider ranging from not ill to severely ill
- [ ] Link it to the API

**Comment by ste519** [comment]
Hi @pyritewolf ! I have created a new route for the mood tracker (slider) on my branch, should I make a new issue or just check the 3rd item of this issue? And should I link my pull request with this issue?

**Comment by pyritewolf** [comment]
Hey @ste519! Great to hear that! Let's just tick off the item here, and yes, link it up:
**The third item is addressed in #53** 

I'll go check the PR in a bit! :)
