### ISSUE TITLE
Terms and Conditions are not required on sign-in, but unclear

### ISSUE THREAD

**Issue by ksl0** [instedd/oasis#214]
The box for "Terms and Conditions" needs to be checked to move onto the sign-in or "Continue as Guest" page, but is relatively subtle.

I think that it would be helpful to have a pop-up error box, or a louder signal to help users get past the first page.

Potentially following this as a template would be helpful: [PR for missing email error](https://github.com/instedd/oasis/pull/212)

**Comment by yus252** [comment]
Right now we do have a warning like this:

![image](https://user-images.githubusercontent.com/37783082/88746644-dd86e880-d101-11ea-8622-1a783008d163.png)

Do you have any suggestions?
