### ISSUE TITLE
Get user actions based on status

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#23]
- [ ] generate an endpoint on the backend that, based on a user's status (sick / not sick, tested / not tested, etc) returns different resources to be displayed in the frontend
    - This still needs some design as to what actionable items are needed on each set of conditions
- [ ] Use that to display actionable items to the user once they're onboarded

**Comment by pyritewolf** [comment]
@nditada a simplified version of this is the issue we should be prioritising for next week, right?

Do we know what's the link that we should display, and what are the exact conditions?

**Comment by nditada** [comment]
The simplified version for this week's demo could simply be to hardcode the links in the front-end.

**Comment by nditada** [comment]
The conditions are: country_of_citizenship == US AND country_of_residence == Mexico. I'll get the links.

**Comment by nditada** [comment]
Link for that condition: "Infor for US citizens" https://mx.usembassy.gov/u-s-citizen-services/covid-19-information/
