### ISSUE TITLE
Exposure notification (anonymous)

### ISSUE THREAD

**Issue by nditada** [instedd/oasis#3]
After a C+ reports to have been in contact with someone, trigger an anonymous email to that person with the following text:

`Dear FirstName, this is a notice informing that you have been may have been  exposed to individuals (contacts) infected with the COVID-19 virus

Please go to myoasis.ucsd.edu for more information and to report how you are feeling. 
You are  encouraged to stay home and maintain social distance from others (at least 6 feet) until 14 days after your last exposure, in case you also become ill. 

You should monitor yourself by checking your temperature twice daily and watching for cough or shortness of breath. 

If you develop symptoms you should promptly isolate yourself and notify your doctor or public health staff. 

You should be promptly evaluated for infection and for the need for medical care.
You can learn more about how to care for yourself if you’ve been exposed here: link 
https://www.sandiegocounty.gov/content/dam/sdc/hhsa/programs/phs/Epidemiology/COVID-19%20Home%20Quarantine%20Guidance.pdf
https://www.cdc.gov/coronavirus/2019-ncov/php/public-health-recommendations.html
`

**Comment by nditada** [comment]
@ easpencer a few assumptions we are making for this:
1- We will only send emails when someone sets their status as "sick".
2- We need to be mindful of not spamming and not be classified by servers as spammers. We will store notifications sent and check before sending emails that the person has not received on in n days (n ~=5?) 
3-The first link is specific to San Diego, for now we will not have conditional on the mailing, so we won't include that link.

**Comment by nditada** [comment]
A few adjustments on the text:

Subject: COVID-19 - Important notification

```
Hello. This is a notice informing that you have been may have been exposed to individuals (contacts) infected with the COVID-19 virus

Someone that has been tested positive, has informed that they might have been in contact with you and provided your email address. To protect everybody's privacy we keep these notifications anonymous. We only have your email address and we will not use it for anything else other than this notification.

Please go to myoasis.ucsd.edu for more information and to report how you are feeling.
You are encouraged to stay home and maintain social distance from others (at least 6 feet) until 14 days after your last exposure, in case you also become ill.

You should monitor yourself by checking your temperature twice daily and watching for cough or shortness of breath.

If you develop symptoms you should promptly isolate yourself and notify your doctor or public health staff.

You should be promptly evaluated for infection and for the need for medical care.
You can learn more about how to care for yourself if you’ve been exposed here: link
https://www.sandiegocounty.gov/content/dam/sdc/hhsa/programs/phs/Epidemiology/COVID-19%20Home%20Quarantine%20Guidance.pdf
https://www.cdc.gov/coronavirus/2019-ncov/php/public-health-recommendations.html
```

**Comment by easpencer** [comment]
Ok, let me take one more stab at editing this text.  And I will find pick a general link for what to do if you are exposed.  

E

**Comment by easpencer** [comment]
https://docs.google.com/document/d/1RoWDB72AApENGO1cpikC_7MqFZZNyd9uSFbIqILtJBk

Moved core text here.  Camille Nebeker is Doing a quick ethics and language check now.
