### ISSUE TITLE
Add a "other symptoms" free text with autocomplete

### ISSUE THREAD

**Issue by nditada** [instedd/oasis#34]
Allow people to report any other symptoms in the assessment, but try to snap the text to a suggestion in a list, using autocomplete. Trying to get a good list of symptoms to use for this.

**Comment by nditada** [comment]
Duplicate of #1 ... getting old...

**Comment by pyritewolf** [comment]
#1 didn't have the autocomplete, though, right @nditada ?

**Comment by nditada** [comment]
It does have a "Need the library for auto-complete." in the description.
