### ISSUE TITLE
Remove "When did you start to feel sick" if you said you're not sick

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#39]
Right now, you see a "when did you start to feel sick" question even if you explicitly said you're ok. Maybe we should remove it?
- [x] Change frontend logic to display this question only when necessary
- [x] Change backend to make the field optional

**Comment by pyritewolf** [comment]
@nditada this is something that Ani noticed while working on this slice of the frontend.

Do you know if this field HAS to be there even if you said you're nice and healthy?

**Comment by nditada** [comment]
No, it should not! Let's remove it.
