### ISSUE TITLE
Display Choropleth adapting by zoom level

### ISSUE THREAD

**Issue by nditada** [instedd/oasis#48]
Ideally show active cases, if not available show total cases.

https://docs.mapbox.com/mapbox-gl-js/example/updating-choropleth/

**Comment by easpencer** [comment]
The ask / feedback from the Embassy group and county team were
1) Set the Map to show the country/region/state (most granular available) level
2) Allow user to manipulate map
3) Color density by zip(postal code)/region/country
4) Ideally show the #reported cases for that zoom level 
5) Ideally show if the reported cases is increasing or decreasing (3 day average)
