### ISSUE TITLE
Update Medical Conditions and Risk Factors Text 

### ISSUE THREAD

**Issue by easpencer** [instedd/oasis#49]
Medical conditions and other risk factors
Asthma (moderate-to-severe)
Chronic kidney disease being treated with dialysis
Chronic lung disease
Diabetes
Hemoglobin Disorder
Immunocompromised
Liver disease
Serious heart condition
Severe obesity
Live in a nursing home or long-term care facility
Active Smoker

**Comment by anaPerezGhiglia** [comment]
@easpencer this list should replace the one that is currently being displayed right? 
or we should add this conditions to the current list?

**Comment by easpencer** [comment]
This replaces the current list

**Comment by easpencer** [comment]
Correct
