### ISSUE TITLE
Update Links and front end logic for display per Embassy request 

### ISSUE THREAD

**Issue by easpencer** [instedd/oasis#50]
People at higher risk (any if age>64, or if yes to any medical conditions) 
https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/people-at-higher-risk.html

HomeBound link (any if sick)
https://earth2-covid.ucsd.edu/homebound

Find clinical trials 
If Healthcare workers: 
https://heroesresearch.org
All in US
https://www.niaid.nih.gov/diseases-conditions/covid-19-clinical-research
All  
https://clinicaltrials.gov/ct2/who_table

Recovered patients in US (if recovered)
 “Donate your blood” link
https://www.redcrossblood.org/donate-blood/dlp/plasma-donations-from-recovered-covid-19-patients.html#donorform

For more information about COVID-19
General (all) 
Coronavirus.gov
Who.net/covid-19
For U.S. Citizens living in Mexico (only México expats)
https://mx.usembassy.gov/u-s-citizens-in-mexico-covid-19-information/
For all us citizens living abroad (is citizen and not living in us) 
https://travel.state.gov/content/travel/en/international-travel/emergencies/what-state-dept-can-cant-do-crisis.html

**Comment by pyritewolf** [comment]
@easpencer some comments on this issue!
- **The general information link for the WHO is not working**, so we didn't add it for now
- For the clinical trials, we're displaying the **most relevant link** - so if you're a healthcare worker living in the US, you see the healthcare link.
- Same goes for US citizens living abroad, we're showing the **most relevant link** - so if you're living in Mexico you get the Mexico embassy url!
