### ISSUE TITLE
Flow issues found during QA

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#78]
- [x] Fix back button in `<Symptoms />` component to use the `history` back method
- [x] "Add my story" isn't working at all - you can't type.
- [x] The form contents in `<Questions />` should be loaded from the API
- [x] The link in `<Alert />` is broken

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/oasis/commit/e0960904d123600eeee914052934efbabfe4d617
