### ISSUE TITLE
Map: Fetch US counties covid data from api

### ISSUE THREAD

**Issue by anaPerezGhiglia** [instedd/oasis#86]
Currently the us-counties covid cases are hardcoded, use api instead

**Comment by pyritewolf** [comment]
[This](https://github.com/instedd/oasis/blob/497c0885f4dcd35a382fe1464fd30f4da6c5eb30/frontend/src/components/Map/index.js) old version of the `<Map />` component has a counties tiling that may come in handy!

**Comment by anaPerezGhiglia** [comment]
Particularly, the tiles source that was being used was
```javascript
source: {
  type: "vector",
  tiles: [
    "https://gis-server.data.census.gov/arcgis/rest/services/Hosted/VT_2017_050_00_PY_D1/VectorTileServer/tile/{z}/{y}/{x}.pbf",
  ],
},
```

**Comment by yus252** [comment]
#164
