### ISSUE TITLE
Autofocus map on current user location

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#91]
[Here](https://medium.com/better-programming/how-to-detect-the-location-of-your-websites-visitor-using-javascript-92f9e91c095f) are some resources that may come in handy (bear in mind they use jQuery in the examples, but they can easily enough be vanillized 😛 )

We'll avoid using the Geolocation API and go straight for an IP lookup to reduce friction

**Comment by yus252** [comment]
#233
