### ISSUE TITLE
When pressing next an error is thrown if the questions form is empty

### ISSUE THREAD

**Issue by mmuller** [instedd/oasis#97]
**Steps to reproduce:**

1. Navigate to the `questions` form.
2. Press the `next` arrow.

**Obtained result:**
- `401` and `422` errors are thrown.
- The App. redirects to the sign-in.

**Comment by anaPerezGhiglia** [comment]
This was fixed. 
Before the field that was generating problems was `age`
Now you can submit a story with all the fields empty, except the `currentLocation` since it is mandatory
@mmuller is already deployed in staging for QA

**Comment by mmuller** [comment]
Working properly in https://github.com/instedd/oasis/commit/c3072208aee079844b36e7c352fdb77e8ad11ce0
